---
# tasks file for ec3
- include_vars: ./vars/main.yml
- name: ensure apt-get is up to date and install items
  apt:
    name: "{{apt_list}}"
    state: present
    update_cache: yes
  with_vars:
    apt_list:
      - docker
      - vim
      - unzip
      - cifs-utils
- name: Install pip packages
  pip:
    name: "{{pip_list}}"
    state: present
  with_vars:
    pip_list:
      - bottle
      - glances
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
- name: create user
  user:
    name: "{{user.name}}"
    comment: 'The man, the myth, the legend'
    groups: wheel, docker
    append: yes
    state: present
    createhome: yes
- name: Create container folders
  file:
    path: "{{containers_folder}}"
    state: directory
    mode: 0775
    owner: "{{user.name}}"
- import_tasks: utilities.yml
- import_tasks: 'containers/sonarr.yml'
- import_tasks: 'containers/radarr.yml'
- import_tasks: 'containers/jackett.yml'
- import_tasks: 'containers/transmission.yml'
- import_tasks: 'containers/heimdall.yml'
- import_tasks: 'containers/jellyfin.yml'
